ERROR 2018-02-27 14:59:56,482 task 6708 2560 {"result":1,"msg":"发送成功"}
None
ERROR 2018-02-27 14:59:56,482 task 6708 2560 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 92, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-05 18:13:52,528 task 5304 4852 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-05 18:13:52,529 task 5304 4852 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-05 18:13:52,789 task 5304 4852 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 144, in IntegralChange
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-05 18:18:42,437 task 5304 6104 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-05 18:18:42,437 task 5304 6104 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-05 18:18:43,032 task 5304 6104 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 144, in IntegralChange
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-06 12:19:51,233 task 9620 10884 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 144, in IntegralChange
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-06 12:20:05,957 task 9620 10360 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-06 12:20:05,957 task 9620 10360 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-06 12:20:06,180 task 9620 10360 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 144, in IntegralChange
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-06 12:20:18,888 task 9620 10988 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-06 12:20:18,890 task 9620 10988 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-06 12:20:19,227 task 9620 10988 'errcode'
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Apoint\apoint\task.py", line 144, in IntegralChange
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-09 13:37:24,167 task 20468 13792 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-09 13:37:24,167 task 20468 13792 'errcode'
Traceback (most recent call last):
  File "G:\python\Apointment\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-09 15:19:18,447 task 20468 30956 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-09 15:19:18,447 task 20468 30956 'errcode'
Traceback (most recent call last):
  File "G:\python\Apointment\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-09 15:21:55,486 task 18548 29300 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-09 15:21:55,486 task 18548 29300 'errcode'
Traceback (most recent call last):
  File "G:\python\Apointment\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-09 15:23:12,012 task 2476 25120 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-09 15:23:12,013 task 2476 25120 'errcode'
Traceback (most recent call last):
  File "G:\python\Apointment\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
ERROR 2018-03-09 15:27:04,493 task 1864 22872 {"result":1,"msg":"发送成功"}
None
ERROR 2018-03-09 15:27:04,493 task 1864 22872 'errcode'
Traceback (most recent call last):
  File "G:\python\Apointment\apoint\task.py", line 106, in ModelNews
    if (eval(r.content)['errcode'] != 0):
KeyError: 'errcode'
